# Generated by Django 5.2.7 on 2025-10-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "work_done",
                    models.TextField(
                        help_text="What did you accomplish? (Markdown supported)"
                    ),
                ),
                (
                    "blockers",
                    models.TextField(blank=True, help_text="What's blocking progress?"),
                ),
                ("next_steps", models.TextField(blank=True, help_text="What's next?")),
                ("hours_worked", models.FloatField(default=0)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("frustrated", "😤 Frustrated"),
                            ("stuck", "🤔 Stuck"),
                            ("neutral", "😐 Neutral"),
                            ("productive", "😊 Productive"),
                            ("flow", "🔥 In Flow"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(blank=True, upload_to="devlogs/%Y/%m/"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
