# Generated by Django 5.2.7 on 2025-10-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code_name", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(max_length=50)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("unity", "Unity"),
                            ("godot", "Godot"),
                            ("unreal", "Unreal Engine"),
                            ("gamemaker", "GameMaker"),
                            ("construct", "Construct"),
                            ("custom", "Custom Engine"),
                            ("web", "Web (HTML5/JS)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "💭 Concept"),
                            ("prototype", "🔨 Prototype"),
                            ("production", "🚀 Production"),
                            ("polish", "✨ Polish"),
                            ("released", "🎮 Released"),
                            ("shelved", "📦 Shelved"),
                        ],
                        default="concept",
                        max_length=20,
                    ),
                ),
                ("target_release", models.DateField(blank=True, null=True)),
                ("actual_release", models.DateField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True)),
                ("itch_url", models.URLField(blank=True)),
                ("steam_url", models.URLField(blank=True)),
                ("is_jam_game", models.BooleanField(default=False)),
                ("jam_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("mac", "macOS"),
                            ("linux", "Linux"),
                            ("webgl", "WebGL"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("build_date", models.DateTimeField(auto_now_add=True)),
                ("changelog", models.TextField()),
                ("file_url", models.URLField(blank=True)),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                ("is_stable", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-build_date"],
            },
        ),
    ]
