# Generated by Django 5.2.7 on 2025-10-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("sprite", "🖼️ Sprite"),
                            ("texture", "🎨 Texture"),
                            ("model_3d", "🎮 3D Model"),
                            ("audio_music", "🎵 Music"),
                            ("audio_sfx", "🔊 Sound Effect"),
                            ("animation", "🏃 Animation"),
                            ("shader", "✨ Shader"),
                            ("font", "🔤 Font"),
                            ("document", "📄 Document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("wip", "Work in Progress"),
                            ("review", "Needs Review"),
                            ("final", "Final"),
                        ],
                        default="concept",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="assets/%Y/%m/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="thumbnails/%Y/%m/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        help_text="e.g., CC0, Purchased, Original",
                        max_length=100,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="If from asset store or external source"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
