# Generated by Django 5.2.7 on 2025-10-17 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "💻 Programming"),
                            ("art_2d", "🎨 2D Art"),
                            ("art_3d", "🎮 3D Modeling"),
                            ("animation", "🏃 Animation"),
                            ("audio_music", "🎵 Music"),
                            ("audio_sfx", "🔊 Sound Effects"),
                            ("level_design", "🗺️ Level Design"),
                            ("game_design", "🎲 Game Design"),
                            ("ui_ux", "📱 UI/UX"),
                            ("narrative", "📝 Story/Narrative"),
                            ("marketing", "📢 Marketing"),
                            ("bugs", "🐛 Bug Fixes"),
                            ("polish", "✨ Polish/Juice"),
                            ("optimization", "⚡ Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("blocker", "🔴 Game Breaking"),
                            ("critical", "🟠 Critical"),
                            ("major", "🟡 Major"),
                            ("minor", "🟢 Minor"),
                            ("polish", "🔵 Nice to Have"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "In Review"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("estimated_hours", models.FloatField(blank=True, null=True)),
                ("actual_hours", models.FloatField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
