# Generated by Django 5.2.7 on 2025-10-17 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reproduction_steps",
                    models.TextField(help_text="Steps to reproduce the bug"),
                ),
                ("expected_behavior", models.TextField()),
                ("actual_behavior", models.TextField()),
                (
                    "level_scene",
                    models.CharField(
                        blank=True, help_text="Which level or scene?", max_length=100
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocker", "🔴 Blocker"),
                            ("critical", "🟠 Critical"),
                            ("major", "🟡 Major"),
                            ("minor", "🟢 Minor"),
                            ("trivial", "⚪ Trivial"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't Fix"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("screenshot", models.ImageField(blank=True, upload_to="bugs/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "build_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.build",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_bugs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-created_at"],
            },
        ),
    ]
